# all commands by default will run on every push, not every commit
default_install_hook_types: [pre-push]
default_stages: [push]

# some configs are only available after v2.18
minimum_pre_commit_version: '2.18'

repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.2.1
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: [
          'dbt-snowflake==1.2.0',
          'sqlfluff-templater-dbt==1.2.1'
        ]
      - id: sqlfluff-fix
        stages: [manual]  # this command is available only to run manually
        additional_dependencies: [
          'dbt-snowflake==1.2.0',
          'sqlfluff-templater-dbt==1.2.1'
        ]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  - repo: https://github.com/Montreal-Analytics/dbt-gloss
    rev: 1.0.1
    hooks:
      - id: dbt-docs-generate
      - id: check-source-table-has-description
      - id: check-model-columns-have-desc
      - id: check-model-has-all-columns
      - id: check-model-has-tests
        args: ["--test-cnt", "2", "--"]
